### ISSUE TITLE
USB signals swapped on MCU

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#21]
![image](https://user-images.githubusercontent.com/1595938/198114563-42f49abf-9c65-4885-9ba1-2e4fd24bf565.png)

Correct:
![image](https://user-images.githubusercontent.com/1595938/198114603-0be9e477-daab-47dc-bb08-8b0b9cbbafea.png)

**Comment by dakoko** [comment]
Swapped the USB signals to be the right way around
