### ISSUE TITLE
Add decoupling capacitors to all MCU power pins

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#22]
There are currently 2 sets of decoupling capacitors:
![image](https://user-images.githubusercontent.com/1595938/198115111-13b422a0-c7bc-47ae-8f81-ab3ea8c206c7.png)

But 3 power pins (2x VDD, 1x VDDA):
![image](https://user-images.githubusercontent.com/1595938/198115217-dc643699-9e87-4845-95e5-bea9ece0f196.png)

**Comment by dakoko** [comment]
Added another set of decoupling capacitors for the MCU
