### ISSUE TITLE
Overlapping schematic objects

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#25]
![image](https://user-images.githubusercontent.com/1595938/198887960-8ad900bf-29aa-41dc-9530-7a5b9bf8bdc5.png)
![image](https://user-images.githubusercontent.com/1595938/198887971-7ca12920-6a25-4e0f-af48-f939242791a3.png)

**Comment by dakoko** [comment]
Fixed the overlap on the schematic

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/199570366-24dba510-8b03-42b3-a495-9ea78d7ab443.png)

**Comment by dakoko** [comment]
Fixed the overlap for c14
