### ISSUE TITLE
DRVOFF does not need to be connected to MCU

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#28]
![image](https://user-images.githubusercontent.com/1595938/198888486-f6fef117-3acf-4f9a-8ab2-66a837668cc3.png)

DRVOFF can be connected to GND to keep motor driver constantly enabled.

This would allow to free up one isolator pin and allow to use smaller 2-channel isolator.

**Comment by dakoko** [comment]
Removed the DRVOFF pin connections, however I still argue for having 3 4-channel isolators as three of the outputs are needed at the top of the board. Replacing it with a 2 channel isolator would needlessly lengthen the signal traces (and also cut into the copperless area inbetween the isolated grounds).
