### ISSUE TITLE
PA1 pin used for ball sensor is not 5V tolerant

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#32]
![image](https://user-images.githubusercontent.com/1595938/200174267-5050d7f4-9565-44cc-9a8d-b6fdf6479338.png)

From [datasheet](https://www.st.com/resource/en/datasheet/stm32g441kb.pdf):
![image](https://user-images.githubusercontent.com/1595938/200167799-820936fe-0732-431a-b46e-b3d8ca1b840a.png)
![image](https://user-images.githubusercontent.com/1595938/200174227-c676cb7f-bfa4-47cb-b1ee-292d5c5c3b3f.png)

**Comment by dakoko** [comment]
The output signal of the ball sensor is going to be brought down to 3.3v with the offboard electronics needed for the sensor. Most likely through a voltage divider.

**Comment by ReikoR** [comment]
It would be easier to use one of the 5V tolerant pins. For example PF0 or PF1:
![image](https://user-images.githubusercontent.com/1595938/200179516-39335021-5995-4411-b519-7e72b4b3d03e.png)

**Comment by dakoko** [comment]
Switched the signal led pin (PF1) with the ball sensor pin (PA1)
