### ISSUE TITLE
Use wider motor driver output connections

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#34]
![image](https://user-images.githubusercontent.com/1595938/200174922-bb2471f0-0bb4-4b47-9f45-14fe001804e4.png)

Polygons can be used:
![image](https://user-images.githubusercontent.com/1595938/200175154-d575b3bc-c659-491b-b73f-c256f8981b69.png)

Pads could also be placed right next to the drivers:
![image](https://user-images.githubusercontent.com/1595938/200175258-e75f9b1d-3ece-4f35-910e-a07f98d92353.png)

**Comment by dakoko** [comment]
Placed the pads next to the drivers and rerouted traces to create less dead copper.
