### ISSUE TITLE
Avoid routing tracks next to each other

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#36]
![image](https://user-images.githubusercontent.com/1595938/200855055-96d8a044-9c5b-48a3-be43-9451addba56b.png)

Signals from one track will couple into adjacent tracks and cause noise.

**Comment by dakoko** [comment]
Dismantled the buses, most have significantly more room between them now.

**Comment by ReikoR** [comment]
Still some improvements that could be made:

![image](https://user-images.githubusercontent.com/1595938/200927289-e2327f5c-88cb-41d3-8dc7-e11f6b51cc4e.png)
![image](https://user-images.githubusercontent.com/1595938/200927583-47354105-0baa-4538-9b58-6a68b566a049.png)

![image](https://user-images.githubusercontent.com/1595938/200927865-869440bd-b55f-4ddd-adaf-feccb42f1fac.png)
![image](https://user-images.githubusercontent.com/1595938/200929201-4e5fd3c1-8552-4c50-b9a4-b19d874ce9a2.png)

**Comment by dakoko** [comment]
Followed the suggested improvements.
