### ISSUE TITLE
Place GND vias close to components

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#37]
For example:
![image](https://user-images.githubusercontent.com/1595938/200856449-90a49009-94c7-488c-8af0-0fc7859b2975.png)

**Comment by dakoko** [comment]
Added lots of vias.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/200934300-9761f9f2-44d6-4848-9966-8fb4ebbf90e7.png)

**Comment by dakoko** [comment]
Suggested locations are directly above 2 power rails, is it really worth putting a hole through VBAT?
![image](https://user-images.githubusercontent.com/36070476/200951394-3e582983-9760-40e4-ba98-67a58bb393f0.png)

**Comment by ReikoR** [comment]
5V track can be moved. Having it next to VBAT is not good anyway.

Something like this:
![image](https://user-images.githubusercontent.com/1595938/201011227-4b91e50e-1929-41c0-aed1-4cf817b32e1c.png)

**Comment by dakoko** [comment]
Moved the trace
