### ISSUE TITLE
LEDs at the bottom

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#38]
![image](https://user-images.githubusercontent.com/1595938/200862855-7c185dcd-1b7a-41c6-ac59-b2a989a72d04.png)

Not sure how you will attach the PCB to the robot, but LEDs might not be visible on the robot or even off the robot.

**Comment by dakoko** [comment]
These LEDs will be used for firmware debugging with an open robot where the PCB isn't attached.
