### ISSUE TITLE
Route USB data signals as differential pair

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#39]
More information here:
https://github.com/ut-robotics/picr22-team-gibibot/issues/32

But use JLC7628 stackup as it is cheaper.

For example 8 mil (about 0.2 mm) trace space and 10.28 mil (about 0.26 mm) trace width would work:
![image](https://user-images.githubusercontent.com/1595938/200866780-67b5dbe1-dd22-4750-97ff-ab60f1978ab8.png)

**Comment by dakoko** [comment]
Rerouted the USB data signals to comply with these rules
