### ISSUE TITLE
Create Gerber X2 files

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#40]
Create Gerber X2 layer and drill files and commit them to repository for ordering the manufacturing.

![image](https://user-images.githubusercontent.com/1595938/200867781-5783d813-41e0-4dd1-b1a2-15735160eb85.png)

![image](https://user-images.githubusercontent.com/1595938/200867926-601d2c1b-1295-4259-b01a-54fc9f22cae2.png)

**Comment by dakoko** [comment]
Added the gerber files

**Comment by dakoko** [comment]
Added the updated files

**Comment by ReikoR** [comment]
Add *.gbr files also.

**Comment by dakoko** [comment]
Added the gerber files, i didn't notice that the output folder wasn't included

**Comment by dakoko** [comment]
Added fresh files
