### ISSUE TITLE
Improve switching regulator layout

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#41]
Try to follow guidelines in the [TPS62933 datasheet](https://www.ti.com/lit/ds/symlink/tps62933.pdf) under 12.1 Layout Guidelines.

1. C6 capacitor should be at the output:
![image](https://user-images.githubusercontent.com/1595938/200871569-c5367a23-d8ca-43c2-82b6-a10ee919f252.png)

2. VIN and GND connections should be wider and with more vias.
\
From datasheet:
The VIN and GND traces must be as wide as possible and provide sufficient vias on them to minimize trace impedance. The wide areas are also of advantage from the view point of heat dissipation.
\
![image](https://user-images.githubusercontent.com/1595938/200872519-2b31001d-e554-4d5d-9228-4a886066a0ba.png)

3. SW connection should be wider.
\
From datasheet:
Keep the SW trace as physically short and wide as practical to minimize radiated emissions.
\
![image](https://user-images.githubusercontent.com/1595938/200873551-0acd4f3b-e757-4222-b5d7-2b973780bc7f.png)

4. Route feedback trace further away from the switching trace. In the current layout it's hard to route it through bottom layer, but it can be routed a bit farther from the inductor. It should also connect to output capacitors.
\
From datasheet:
Place the voltage feedback loop away from the high-voltage switching trace. The voltage feedback loop preferably has ground shield.
\
![image](https://user-images.githubusercontent.com/1595938/200874749-3e73d41a-dee5-4391-b87c-af6ea7c295c1.png)

**Comment by dakoko** [comment]
Alleviated the issues, don't know if it's enough though.

**Comment by ReikoR** [comment]
It's possible to make SW copper a bit wider by moving the regulator downwards.

Before:
![image](https://user-images.githubusercontent.com/1595938/201011688-84b99024-9e73-45a4-a9e3-2b76f52f6a68.png)

After:
![image](https://user-images.githubusercontent.com/1595938/201014832-015ceb77-c158-486d-8b18-f78a30826cf5.png)

I recommend using Polygon Pour instead of Region. Polygons automatically pour based on the rules.

Polygons:
![image](https://user-images.githubusercontent.com/1595938/201015184-439caceb-636c-4d91-a640-3eb15c52338c.png)

Regulator input GND polygon properties:
![image](https://user-images.githubusercontent.com/1595938/201015321-627ff609-6af9-405f-a6f9-863cf022736b.png)

I created a Polygon Connect Style rule to use direct connection for these polygons:
![image](https://user-images.githubusercontent.com/1595938/201015521-aa8bd2fa-fe23-4c90-8825-f521a029653f.png)
`InNet('NetC13_1') or InNet('VBAT') or ((ObjectKind = 'Poly') And (Name = 'GND_SWREG_IN')) `

Pour order also needs to be changed in Polygon Manager (Tools -> Polygon Pours -> Polygon Manager):
![image](https://user-images.githubusercontent.com/1595938/201016141-c46c797e-99a8-48f1-9da6-41a49a01dede.png)
Smaller polygons need to poured before larger GND polygon.

**Comment by dakoko** [comment]
Replaced the regions with pours

**Comment by ReikoR** [comment]
There are very thin gaps next to the GND polygon:
![image](https://user-images.githubusercontent.com/1595938/201202244-fca4c948-8bce-4d80-9a25-1e004123af41.png)

**Comment by dakoko** [comment]
Added thermal relief and fixed the thin gap issue

**Comment by ReikoR** [comment]
It would be better to have GND directly connected.

**Comment by dakoko** [comment]
Connected it directly
