### ISSUE TITLE
Remove dead copper

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#44]
There's some unconnected copper:
![image](https://user-images.githubusercontent.com/1595938/200930667-78c2f010-73a7-45b9-9886-6ae11992276c.png)

Unconnected copper and even connected copper can cause more crosstalk.
Some more info about copper fills and crosstalk: https://youtu.be/y4REmZlE7Jg?t=2415

**Remove Dead Copper** should be checked in Polygon Pour properties:
![image](https://user-images.githubusercontent.com/1595938/200931060-74ce1d47-6a1e-4916-9312-0a3888d3df36.png)

**Comment by dakoko** [comment]
Removed dead copper and other useless copper islands that were attached with vias (for no reason).
The video was insightful but it seems that a significant amount of people disagreed with his reasoning which has left me a bit conflicted on how applicable his example situation is in different scenarios.
