### ISSUE TITLE
[Mechanics] camera mount interlocks with top plate

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-owo#46]
A question about the top plate - camera mount interface.

Why should they lock in with each other? Would it not increase assembly complexity by a lot? Are there any benefits to doing it compared to not doing it?

![image](https://user-images.githubusercontent.com/5435954/201523719-f674913a-6af8-49b2-aed9-1410cb26d961.png)

**Comment by Rxsengxn** [comment]
Yes it does increase assembly complexity but not that much. During first assembly, it is needed to slide them through top plate and lock them, that's all the increased complexity. After the assembly, when it's needed to get inside the robot, only the bottom plate camera mount screws need to be unscrewed in addition to other common part's screws for it to come off. With this design, we aim to make the camera to be as stable as it could be with stiff mount.
