### ISSUE TITLE
[Mechanics] different screw holes

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-owo#49]
Is it intentional to have different hole styles in the same area?

![image](https://user-images.githubusercontent.com/5435954/201524455-8062d659-9ee2-43d2-bb94-3cc64451eb2c.png)

**Comment by Akustav** [comment]
Same here:

![image](https://user-images.githubusercontent.com/5435954/201524506-c3011a39-37fc-4fc4-ab82-a10ed75c457b.png)

**Comment by Rxsengxn** [comment]
These are somewhat intentional, yes. In general we used cone-shaped screws where really needed, and cylinder, where it doesn't matter that much. We could make them all cones if needed
